server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

jwtconfig:
  secret: secret
  expiration: 6000000

currency:
  client:
    url: "http://www.cbr.ru/scripts/XML_daily.asp"

#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true
